version: '3.9'
services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: unless-stopped
    hostname: 'gitlab'
    container_name: gitlab
    environment:
      # GITLAB_OMNIBUS_CONFIG: "from_file('/omnibus_config.rb')"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.2.100'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        letsencrypt['enabled'] = false
        nginx['redirect_http_to_https'] = true
    configs:
      - source: gitlab
        target: /omnibus_config.rb
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '${GITLAB_HOME}/config:/etc/gitlab'
      - '${GITLAB_HOME}/logs:/var/log/gitlab'
      - '${GITLAB_HOME}/data:/var/opt/gitlab'
configs:
  gitlab:
    file: ./gitlab.rb
